# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/auth.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11protos/auth.proto\"\xcd\x01\n\x0b\x41uthRequest\x12%\n\x06phase1\x18\x01 \x01(\x0b\x32\x13.AuthRequest.Phase1H\x00\x12%\n\x06phase2\x18\x02 \x01(\x0b\x32\x13.AuthRequest.Phase2H\x00\x12%\n\x06phase3\x18\x03 \x01(\x0b\x32\x13.AuthRequest.Phase3H\x00\x1a\"\n\x06Phase1\x12\r\n\x05uname\x18\x01 \x01(\t\x12\t\n\x01\x41\x18\x02 \x01(\x0c\x1a\x13\n\x06Phase2\x12\t\n\x01M\x18\x01 \x01(\x0c\x1a\x08\n\x06Phase3B\x06\n\x04\x62ody\"\xdf\x01\n\x0c\x41uthResponse\x12&\n\x06phase1\x18\x01 \x01(\x0b\x32\x14.AuthResponse.Phase1H\x00\x12&\n\x06phase2\x18\x02 \x01(\x0b\x32\x14.AuthResponse.Phase2H\x00\x12&\n\x06phase3\x18\x03 \x01(\x0b\x32\x14.AuthResponse.Phase3H\x00\x1a\x1e\n\x06Phase1\x12\t\n\x01s\x18\x01 \x01(\x0c\x12\t\n\x01\x42\x18\x02 \x01(\x0c\x1a\x16\n\x06Phase2\x12\x0c\n\x04HAMK\x18\x01 \x01(\x0c\x1a\x17\n\x06Phase3\x12\r\n\x05token\x18\x01 \x01(\tB\x06\n\x04\x62ody26\n\x04\x41uth\x12.\n\tAuthorize\x12\x0c.AuthRequest\x1a\r.AuthResponse\"\x00(\x01\x30\x01\x62\x06proto3')



_AUTHREQUEST = DESCRIPTOR.message_types_by_name['AuthRequest']
_AUTHREQUEST_PHASE1 = _AUTHREQUEST.nested_types_by_name['Phase1']
_AUTHREQUEST_PHASE2 = _AUTHREQUEST.nested_types_by_name['Phase2']
_AUTHREQUEST_PHASE3 = _AUTHREQUEST.nested_types_by_name['Phase3']
_AUTHRESPONSE = DESCRIPTOR.message_types_by_name['AuthResponse']
_AUTHRESPONSE_PHASE1 = _AUTHRESPONSE.nested_types_by_name['Phase1']
_AUTHRESPONSE_PHASE2 = _AUTHRESPONSE.nested_types_by_name['Phase2']
_AUTHRESPONSE_PHASE3 = _AUTHRESPONSE.nested_types_by_name['Phase3']
AuthRequest = _reflection.GeneratedProtocolMessageType('AuthRequest', (_message.Message,), {

  'Phase1' : _reflection.GeneratedProtocolMessageType('Phase1', (_message.Message,), {
    'DESCRIPTOR' : _AUTHREQUEST_PHASE1,
    '__module__' : 'protos.auth_pb2'
    # @@protoc_insertion_point(class_scope:AuthRequest.Phase1)
    })
  ,

  'Phase2' : _reflection.GeneratedProtocolMessageType('Phase2', (_message.Message,), {
    'DESCRIPTOR' : _AUTHREQUEST_PHASE2,
    '__module__' : 'protos.auth_pb2'
    # @@protoc_insertion_point(class_scope:AuthRequest.Phase2)
    })
  ,

  'Phase3' : _reflection.GeneratedProtocolMessageType('Phase3', (_message.Message,), {
    'DESCRIPTOR' : _AUTHREQUEST_PHASE3,
    '__module__' : 'protos.auth_pb2'
    # @@protoc_insertion_point(class_scope:AuthRequest.Phase3)
    })
  ,
  'DESCRIPTOR' : _AUTHREQUEST,
  '__module__' : 'protos.auth_pb2'
  # @@protoc_insertion_point(class_scope:AuthRequest)
  })
_sym_db.RegisterMessage(AuthRequest)
_sym_db.RegisterMessage(AuthRequest.Phase1)
_sym_db.RegisterMessage(AuthRequest.Phase2)
_sym_db.RegisterMessage(AuthRequest.Phase3)

AuthResponse = _reflection.GeneratedProtocolMessageType('AuthResponse', (_message.Message,), {

  'Phase1' : _reflection.GeneratedProtocolMessageType('Phase1', (_message.Message,), {
    'DESCRIPTOR' : _AUTHRESPONSE_PHASE1,
    '__module__' : 'protos.auth_pb2'
    # @@protoc_insertion_point(class_scope:AuthResponse.Phase1)
    })
  ,

  'Phase2' : _reflection.GeneratedProtocolMessageType('Phase2', (_message.Message,), {
    'DESCRIPTOR' : _AUTHRESPONSE_PHASE2,
    '__module__' : 'protos.auth_pb2'
    # @@protoc_insertion_point(class_scope:AuthResponse.Phase2)
    })
  ,

  'Phase3' : _reflection.GeneratedProtocolMessageType('Phase3', (_message.Message,), {
    'DESCRIPTOR' : _AUTHRESPONSE_PHASE3,
    '__module__' : 'protos.auth_pb2'
    # @@protoc_insertion_point(class_scope:AuthResponse.Phase3)
    })
  ,
  'DESCRIPTOR' : _AUTHRESPONSE,
  '__module__' : 'protos.auth_pb2'
  # @@protoc_insertion_point(class_scope:AuthResponse)
  })
_sym_db.RegisterMessage(AuthResponse)
_sym_db.RegisterMessage(AuthResponse.Phase1)
_sym_db.RegisterMessage(AuthResponse.Phase2)
_sym_db.RegisterMessage(AuthResponse.Phase3)

_AUTH = DESCRIPTOR.services_by_name['Auth']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _AUTHREQUEST._serialized_start=22
  _AUTHREQUEST._serialized_end=227
  _AUTHREQUEST_PHASE1._serialized_start=154
  _AUTHREQUEST_PHASE1._serialized_end=188
  _AUTHREQUEST_PHASE2._serialized_start=190
  _AUTHREQUEST_PHASE2._serialized_end=209
  _AUTHREQUEST_PHASE3._serialized_start=211
  _AUTHREQUEST_PHASE3._serialized_end=219
  _AUTHRESPONSE._serialized_start=230
  _AUTHRESPONSE._serialized_end=453
  _AUTHRESPONSE_PHASE1._serialized_start=366
  _AUTHRESPONSE_PHASE1._serialized_end=396
  _AUTHRESPONSE_PHASE2._serialized_start=398
  _AUTHRESPONSE_PHASE2._serialized_end=420
  _AUTHRESPONSE_PHASE3._serialized_start=422
  _AUTHRESPONSE_PHASE3._serialized_end=445
  _AUTH._serialized_start=455
  _AUTH._serialized_end=509
# @@protoc_insertion_point(module_scope)
